# Permalinks
#
permalink:           :year/:month/:title/

# Setup
title:               R/W
tagline:             'Thought and technical experiments.'
description:         'The place where Clément Renaud write stuff about his current thoughts, works, projects, etc.'
url:                 http://clementrenaud.com/rw
baseurl:             '/rw'

gems: [jekyll-paginate]
paginate:            5

# About/contact
author:
  name:              Clément Renaud
  twitter:               https://twitter.com/clemsos
  email:             hello@clementrenaud.com

# Custom vars
version:             1.0.0
